In [22]:
import numpy as np
import pandas as pd

In [23]:
df = pd.read_csv("Multiple-Linear-Regression.csv")

In [24]:
df.head()

,CGPA,12th_Marks(%),NoOfInternships,Package(LPA)
0,6.87,82.1,0,7.52
1,9.75,54.2,5,12.85
2,8.66,58.1,0,7.27
3,7.99,94.9,0,7.65
4,5.78,80.3,5,10.59


In [25]:
X = df.iloc[:,0:3]

In [26]:
type(X)

pandas.core.frame.DataFrame

In [27]:
y = df.iloc[:,3]

In [28]:
type(y)

pandas.core.series.Series

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [31]:
lr.fit(X_train, y_train)

LinearRegression()

In [32]:
X_test.values

array([[ 7.47, 76.1 ,  5.  ],
       [ 5.92, 61.9 ,  0.  ],
       [ 8.04, 89.7 ,  3.  ],
       [ 6.19, 97.  ,  2.  ],
       [ 5.03, 71.  ,  4.  ],
       [ 9.36, 84.8 ,  6.  ],
       [ 9.93, 64.7 ,  1.  ],
       [ 8.39, 55.  ,  3.  ],
       [ 8.23, 53.6 ,  1.  ],
       [ 8.31, 96.4 ,  5.  ],
       [ 5.7 , 84.9 ,  4.  ],
       [ 9.62, 81.4 ,  6.  ],
       [ 9.18, 69.3 ,  3.  ],
       [ 6.79, 85.1 ,  4.  ],
       [ 9.09, 64.1 ,  4.  ],
       [ 6.93, 51.2 ,  4.  ],
       [ 5.44, 96.8 ,  3.  ],
       [ 5.72, 82.9 ,  6.  ],
       [ 6.65, 68.8 ,  0.  ],
       [ 5.37, 68.  ,  0.  ],
       [ 6.14, 97.7 ,  0.  ],
       [ 6.52, 66.3 ,  2.  ],
       [ 5.26, 68.7 ,  6.  ],
       [ 7.81, 68.  ,  4.  ],
       [ 7.71, 87.  ,  5.  ],
       [ 6.94, 80.8 ,  3.  ],
       [ 6.55, 78.9 ,  6.  ],
       [ 9.01, 85.1 ,  1.  ],
       [ 7.14, 86.9 ,  0.  ],
       [ 5.6 , 50.7 ,  4.  ],
       [ 8.54, 58.  ,  2.  ],
       [ 7.16, 82.5 ,  0.  ],
       [ 9.61, 77.8 ,  6.  ],
       [ 8

In [33]:
y_test.values

array([12.8 ,  6.67, 11.56,  8.73,  8.56, 15.55, 10.2 , 10.06,  7.42,
       14.22,  9.41, 14.27, 11.88,  8.96, 12.82,  9.6 ,  8.62, 10.16,
        6.71,  5.98,  6.46,  8.9 , 10.71, 10.65, 12.55,  8.06, 11.98,
       10.95,  8.24,  8.73, 10.03,  6.52, 13.29, 10.35,  8.57, 11.76,
       11.21, 12.97, 10.71, 12.95])

In [34]:
lr.predict(X_test.iloc[0].values.reshape(1,-1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.47654588])

In [35]:
lr.predict(X_test.iloc[[0]])

array([11.47654588])

In [36]:
lr.predict(X_test.values)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.47654588,  6.15840732, 10.8854079 ,  9.20435272,  8.92292853,
       13.80881651,  9.65539181,  9.76050357,  8.10312642, 12.82217002,
        9.90672121, 13.84712937, 10.8388889 , 10.63184634, 11.3252739 ,
        9.3999885 ,  9.45167956, 11.33917675,  6.90829493,  6.03469997,
        7.70138212,  8.22250966, 10.48186545, 10.63524097, 12.06019424,
        9.81391689, 11.72916531,  9.84668978,  7.93766624,  8.50520596,
        9.2276811 ,  7.77898267, 13.69994781, 11.46532921,  9.0601209 ,
       12.48845034, 10.72463169, 12.52294373, 10.96738246, 12.93025506])

In [37]:
lr.coef_

array([0.65808622, 0.03905575, 0.74870266])

In [38]:
lr.intercept_

np.float64(-0.15501398086244755)

In [39]:
lr.predict([[8.5,94,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.10995932])